name: Enforce Branch Naming

on:
  push:
    branches:
      - '*'

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Naming
        run: |
          pattern="^refs/heads/feature/.*$"
          while read -r ref; do
            branch=$(echo "$ref" | awk -F'/' '{print $4}')
            if [[ ! "$ref" =~ $pattern ]]; then
              echo "Error: Branch name '$branch' does not match the required pattern: feature/.*"
              exit 1
            fi
          done <<< "$(git log --format='%D' -n 1)"
