name: Enforce Branch Naming

on:
  push:
    branches:
      - '*'

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Naming
        run: |
          #!/bin/bash
          pattern="refs/heads/feature/.*"
          while read -r ref; do
            branch=$(echo "$ref" | awk -F'/' '{print $4}')
            if [[ ! "$branch" =~ ^$pattern$ ]]; then
              echo "Error: Branch name '$branch' does not match the required pattern: $pattern"
              exit 1
            fi
          done <<< "$(git log --format='%D' -n 1)"
